from typing import Callable, Iterable, Optional

from openai import OpenAI

from app.config.settings import settings
from app.utils.logger import get_logger


logger = get_logger(__name__)


class LLM:
    """
    OmniRoute LLM client used by the RAG pipeline.

    OmniRoute exposes an OpenAI-compatible API, so this class
    communicates with OmniRoute through the OpenAI Python client.

    The rest of the RAG pipeline can continue using:

        llm.generate(prompt)

    and:

        llm.chat(message)
    """

    def __init__(self):
        """
        Initialize the OmniRoute client.
        """

        if not settings.omniroute_api_key:
            raise ValueError(
                "OMNIROUTE_API_KEY is not configured."
            )

        self.base_url = settings.omniroute_base_url
        self.model = settings.omniroute_model

        self.client = OpenAI(
            api_key=settings.omniroute_api_key,
            base_url=self.base_url,
        )

        logger.info(
            "OmniRoute LLM initialized - model: %s, base_url: %s",
            self.model,
            self.base_url,
        )

    # =========================================================
    # Generate
    # =========================================================

    def generate(
        self,
        prompt: str,
    ) -> str:
        """
        Generate a response using OmniRoute.

        Parameters
        ----------
        prompt : str
            Complete prompt generated by the RAG prompt builder.

        Returns
        -------
        str
            Generated response.
        """

        if not prompt or not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        logger.info(
            "Sending prompt to OmniRoute model: %s",
            self.model,
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ],
            )

            if response is None:
                raise RuntimeError(
                    "OmniRoute returned an empty response."
                )

            if not response.choices:
                raise RuntimeError(
                    "OmniRoute returned no choices."
                )

            text = response.choices[0].message.content

            if not text:
                raise RuntimeError(
                    "OmniRoute returned empty text."
                )

            logger.info(
                "OmniRoute response generated successfully."
            )

            return text.strip()

        except Exception:
            logger.exception(
                "OmniRoute generation failed."
            )
            raise

    # =========================================================
    # Chat
    # =========================================================

    def chat(
        self,
        message: str,
        tools: Optional[Iterable[Callable]] = None,
    ) -> str:
        """
        Send a chat message through OmniRoute.

        Parameters
        ----------
        message : str
            User message.

        tools : Iterable[Callable], optional
            Reserved for future tool/function calling support.

        Returns
        -------
        str
            Generated response.
        """

        if not message or not message.strip():
            raise ValueError(
                "Message cannot be empty."
            )

        logger.info(
            "Starting OmniRoute chat with model: %s",
            self.model,
        )

        try:
            messages = [
                {
                    "role": "user",
                    "content": message,
                }
            ]

            # Basic chat request.
            #
            # Tool support is intentionally not implemented here yet.
            # OmniRoute supports OpenAI-compatible chat completions,
            # so we can add OpenAI-style tools later if required.
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
            )

            if response is None:
                raise RuntimeError(
                    "OmniRoute returned an empty chat response."
                )

            if not response.choices:
                raise RuntimeError(
                    "OmniRoute returned no chat choices."
                )

            text = response.choices[0].message.content

            if not text:
                raise RuntimeError(
                    "OmniRoute returned empty chat text."
                )

            logger.info(
                "OmniRoute chat response generated successfully."
            )

            return text.strip()

        except Exception:
            logger.exception(
                "OmniRoute chat generation failed."
            )
            raise

    # =========================================================
    # Model
    # =========================================================

    def get_model_name(self) -> str:
        """
        Return the configured OmniRoute model name.
        """

        return self.model

    # =========================================================
    # Close
    # =========================================================

    def close(self):
        """
        Close the LLM client.

        The OpenAI client does not require an explicit shutdown
        for normal usage, but this method keeps the interface
        consistent with the rest of the project.
        """

        logger.info(
            "OmniRoute LLM client closed."
        )