"""
LLM interface for the Supply Chain Intelligence RAG pipeline.
"""

from app.config.settings import settings
from app.utils.logger import get_logger


logger = get_logger(__name__)


class LLM:
    """
    Language Model interface.

    This class provides a single interface for generating
    answers from RAG prompts.

    The actual provider/model configuration is taken from
    application settings.
    """

    def __init__(self):
        self.provider = getattr(
            settings,
            "llm_provider",
            "lm_studio",
        )

        self.model = getattr(
            settings,
            "llm_model",
            None,
        )

        self.base_url = getattr(
            settings,
            "llm_base_url",
            None,
        )

        logger.info(
            "LLM initialized with provider: %s",
            self.provider,
        )

    # =========================================================
    # Generate
    # =========================================================

    def generate(
        self,
        prompt: str,
    ) -> str:
        """
        Generate an answer from an LLM prompt.

        Parameters
        ----------
        prompt : str
            Complete prompt generated by PromptBuilder.

        Returns
        -------
        str
            Generated answer.
        """

        if not prompt or not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        if self.provider == "lm_studio":
            return self._generate_lm_studio(
                prompt
            )

        raise ValueError(
            f"Unsupported LLM provider: {self.provider}"
        )

    # =========================================================
    # LM Studio
    # =========================================================

    def _generate_lm_studio(
        self,
        prompt: str,
    ) -> str:
        """
        Generate response using LM Studio's
        OpenAI-compatible API.
        """

        try:
            from openai import APIConnectionError, OpenAI

        except ImportError as exc:
            raise ImportError(
                "openai package is required for LM Studio."
            ) from exc

        if not self.base_url:
            raise ValueError(
                "llm_base_url is not configured."
            )

        if not self.model:
            raise ValueError(
                "llm_model is not configured."
            )

        client = OpenAI(
            base_url=self.base_url,
            api_key="lm-studio",
        )

        logger.info(
            "Sending prompt to LM Studio model: %s",
            self.model,
        )

        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ],
                temperature=0.2,
            )

        except APIConnectionError as exc:
            raise RuntimeError(
                "Could not connect to LM Studio at "
                f"{self.base_url}. Start the LM Studio local server, "
                "confirm the port is correct, and make sure model "
                f"'{self.model}' is loaded."
            ) from exc

        answer = response.choices[0].message.content

        if not answer:
            raise RuntimeError(
                "LLM returned an empty response."
            )

        logger.info(
            "LLM response generated successfully."
        )

        return answer.strip()

    # =========================================================
    # Configuration
    # =========================================================

    def get_provider(self) -> str:
        """
        Return the configured LLM provider.
        """

        return self.provider

    def get_model(self):
        """
        Return the configured LLM model.
        """

        return self.model
